"""Domain models for notification orchestration.

These models intentionally separate business events from delivery concerns so the
rule engine and dispatcher can evolve independently.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, time
from enum import Enum
from typing import Any
from uuid import uuid4


class NotificationChannel(str, Enum):
    """Supported notification channels."""

    MOBILE_PUSH = "mobile_push"
    PERSISTENT = "persistent_notification"


class NotificationSeverity(str, Enum):
    """Severity categories used for prioritization and filtering."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


@dataclass(slots=True)
class QuietHours:
    """Quiet hours window."""

    start: time
    end: time
    timezone: str = "local"


@dataclass(slots=True)
class RuleCondition:
    """Declarative condition expression used by the rule engine."""

    key: str
    operator: str
    value: Any


@dataclass(slots=True)
class NotificationTarget:
    """Target device metadata discovered from Home Assistant notify services."""

    id: str
    service: str
    display_name: str
    platform: str
    user_id: str | None = None
    active: bool = True


@dataclass(slots=True)
class NotificationPreference:
    """Global preferences with defaults used by rules and events."""

    enabled: bool = True
    default_channels: tuple[NotificationChannel, ...] = (
        NotificationChannel.MOBILE_PUSH,
    )
    default_severity: NotificationSeverity = NotificationSeverity.INFO


@dataclass(slots=True)
class NotificationRule:
    """Rule configuration that maps events to notification messages."""

    id: str
    name: str
    enabled: bool
    event_types: tuple[str, ...]
    target_user_ids: tuple[str, ...] = ()
    target_device_ids: tuple[str, ...] = ()
    channels: tuple[NotificationChannel, ...] = ()
    severity: NotificationSeverity = NotificationSeverity.INFO
    cooldown_seconds: int = 0
    quiet_hours: QuietHours | None = None
    conditions: tuple[RuleCondition, ...] = ()
    message_template: str | None = None


@dataclass(slots=True)
class NotificationEvent:
    """Internal business event emitted by shopping workflows."""

    event_type: str
    title: str
    message: str
    payload: dict[str, Any] = field(default_factory=dict)
    severity: NotificationSeverity = NotificationSeverity.INFO
    source: str = "shopping"
    created_at: datetime = field(default_factory=datetime.utcnow)
    correlation_id: str = field(default_factory=lambda: str(uuid4()))


@dataclass(slots=True)
class NotificationMessage:
    """Delivery-ready message generated by rule evaluation."""

    id: str
    event: NotificationEvent
    rule_id: str | None
    target: NotificationTarget
    channels: tuple[NotificationChannel, ...]
    title: str
    body: str
    severity: NotificationSeverity
    click_url: str | None = None
    dedup_key: str | None = None
    mobile_data: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class NotificationHistoryEntry:
    """Result of one dispatch attempt."""

    id: str
    message_id: str
    event_type: str
    rule_id: str | None
    target_id: str
    channels: tuple[NotificationChannel, ...]
    delivered: bool
    delivered_channels: tuple[NotificationChannel, ...] = ()
    error: str | None = None
    created_at: datetime = field(default_factory=datetime.utcnow)


@dataclass(slots=True)
class NotificationSettings:
    """Persisted configuration aggregate."""

    preferences: NotificationPreference = field(default_factory=NotificationPreference)
    targets: list[NotificationTarget] = field(default_factory=list)
    rules: list[NotificationRule] = field(default_factory=list)
    enabled_event_types: tuple[str, ...] = ()
